### ISSUE TITLE
Cargo clippy with cargo-sysroot warns on sysroot

### ISSUE THREAD

**Issue by XAMPPRocky** [DianaNites/cargo-sysroot#6] opened 2020-11-18 14:56 UTC
Hey while working on https://github.com/EmbarkStudios/rust-gpu/pull/239 I noticed that when running `cargo clippy` on a project that uses `cargo-sysroot` in a build script will also run clippy on core, which isn't ideal since there's a lot of warnings, and there's not much I as a user can do about it. It would be nice if clippy didn't warn about sysroot.

**Comment by DianaNites** [comment] 2020-11-18 15:41
Gonna need more information here, as i'm unable to reproduce, and have never had that happen before.

**Comment by XAMPPRocky** [comment] 2020-11-18 15:49
Here's steps to reproduce. I'm running on macOS 11.0.1

1. Clone & Checkout https://github.com/EmbarkStudios/rust-gpu/tree/vuild-system
2. Run `cargo clippy --manifest-path examples/runners/ash/Cargo.toml -vv`

You can also see the output here, as I first noticed on CI. https://github.com/EmbarkStudios/rust-gpu/runs/1418118000?check_suite_focus=true#step:8:333

**Comment by DianaNites** [comment] 2020-11-18 16:07
Does not reproduce on my machine, clippy ran successfully.

**Comment by XAMPPRocky** [comment] 2020-11-18 16:14
Hmm, okay. I can reproduce it here, so I'll try to debug this later this week.

**Comment by DianaNites** [comment] 2020-11-19 15:14
Apologies, seems I out the branch wrong. I'm getting failures, but nothing mentioning core, "Error loading target specification: Could not find specification for target "spirv-unknown-unknown"".
A bunch of warnings for other dependencies under `~/.cargo/registry`, though?

**Comment by XAMPPRocky** [comment] 2020-11-19 15:50
> "Error loading target specification: Could not find specification for target "spirv-unknown-unknown"".
That's actually a different bug, the rustc flags in the builder aren't working.

**Comment by DianaNites** [comment] 2020-11-19 15:57
Yeah oops, I noticed that. Fixed in https://github.com/DianaNites/cargo-sysroot/commit/48f811f9552ee45e63e86c9bdf026da8011f00bb

**Comment by DianaNites** [comment] 2020-11-19 15:58
Now it seems to be linker errors

> librustc_codegen_spirv.so: undefined symbol: _ZN8spvtools3val8Function13current_blockEv"

**Comment by XAMPPRocky** [comment] 2020-11-19 16:04
I have a fix for that locally one moment.

**Comment by XAMPPRocky** [comment] 2020-11-19 16:27
@DianaNites Okay it's working now so running `cargo clippy --manifest-path examples/runners/ash/Cargo.toml -vv` (I recommend trying to compile without `-vv` once, to remove most of the noise) in the `vuild-system` branch should show clippy warnings in the `example-ash` build script.

**Comment by DianaNites** [comment] 2020-11-19 16:36
Clippy now successfully runs, and i'm not seeing any clippy warnings from the sysroot, just all the dependencies?

**Comment by DianaNites** [comment] 2020-11-19 16:41
Ah build output, If I insert a panic into the build script I see non-fatal clippy warnings.

No idea why thats happening..

**Comment by XAMPPRocky** [comment] 2020-11-19 17:35
I’ll investigate more tomorrow, but I would hazard to guess it’s something with flags and or `cargo rustc` causing issues.

**Comment by XAMPPRocky** [comment] 2020-12-01 16:50
Potnentially related: https://github.com/EmbarkStudios/rust-gpu/issues/294

**Comment by DianaNites** [comment] 2021-01-26 21:25
Cause is probably the new `RUSTC_WORKSPACE_WRAPPER`, documented on nightly https://doc.rust-lang.org/nightly/cargo/reference/environment-variables.html, [added specifically for clippy](https://github.com/rust-lang/cargo/pull/7533/)

Removing it from the env should probably fix it

**Comment by DianaNites** [comment] 2021-01-26 21:36
Should be fixed now but I can't test so

**Closed** 2021-01-26 21:36 UTC
Labels: needs-info
